/vtol_gps_mission_node:
  ros__parameters:
    # 1. 미션 경로점 (VTOL 순항 및 구조 지점 접근)
    wp1: [35.06898, 128.0863, 20.0]  # 이륙 및 Home 복귀점
    wp2: [35.06861, 128.0868, 20.0]  # 천이 시작점
    wp3: [35.06737, 128.0873, 20.0]  # 고정익 선회 1
    wp4: [35.06854, 128.0884, 20.0]  # 고정익 선회 2 / 조난자 탐색 진입점
    
    # 2. 임무 핵심 지점
    rescue_loc: [35.06945, 128.0864, 5.0] # 조난자 구조 위치 (호버링 고도)
    
    # 3. 복귀 경로 (역순 지정)
    # 조난자 구조 후 [wp4 -> wp3 -> wp2 -> wp1] 순으로 이동
    return_wps:
      - [35.06854, 128.0884, 15.0]  # WP4 (복귀 고도 상향)
      - [35.06737, 128.0873, 15.0]  # WP3
      - [35.06861, 128.0868, 15.0]  # WP2
      - [35.06898, 128.0863, 10.0]  # WP1 (최종 착륙 접근 고도)

    # 4. 시스템 파라미터
    safe_ascend_alt: 15.0 # 구조 후 안전 상승 고도
